Repository pacutil/pacu, pull requests merged in 2025-04, with the labels that each got.

#28 Corrigir a função strip_url()
  src/features/distribution_features.py
  src/features/test_distribution_features.py
Labels: bug

#48 Brief description on feature functions
  src/pacu/features/distribution_features.py
  src/pacu/features/lexical_features.py
Labels: documentation

#55 handle possible ValueError in has_port()
  src/pacu/features/lexical_features.py
Labels: bug

#62 drop url column after extraction
  src/pacu/features/features.py
  src/pacu/train.py
Labels: enhancement

#69 fix tests and bigram_dist() type annotations
  src/pacu/features/distribution_features.py
  src/pacu/features/test_distribution_features.py
Labels: bug
